// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkW_GzvW_Vby2FoeW_JHW4WMLs2eT7De8',
    appId: '1:806810511020:web:f302d79596a4b87f956109',
    messagingSenderId: '806810511020',
    projectId: 'nft-project-9e107',
    authDomain: 'nft-project-9e107.firebaseapp.com',
    storageBucket: 'nft-project-9e107.appspot.com',
    measurementId: 'G-TTHE7VRYMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8U1iaSU6vJBH4UCaKV67FN9KA-Hf3r0',
    appId: '1:806810511020:android:96fb2cfa0ff71304956109',
    messagingSenderId: '806810511020',
    projectId: 'nft-project-9e107',
    storageBucket: 'nft-project-9e107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDElTYGEV_dm3I1HyHt8d_GyhXyQeiQ0hk',
    appId: '1:806810511020:ios:6fa4502a798da86b956109',
    messagingSenderId: '806810511020',
    projectId: 'nft-project-9e107',
    storageBucket: 'nft-project-9e107.appspot.com',
    androidClientId: '806810511020-l0l33tje27n2fio4e0vdkn75m26a8n62.apps.googleusercontent.com',
    iosClientId: '806810511020-coiqoj23j7ssb4k6lc3rg8uc48adueie.apps.googleusercontent.com',
    iosBundleId: 'com.application.nftFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDElTYGEV_dm3I1HyHt8d_GyhXyQeiQ0hk',
    appId: '1:806810511020:ios:6fa4502a798da86b956109',
    messagingSenderId: '806810511020',
    projectId: 'nft-project-9e107',
    storageBucket: 'nft-project-9e107.appspot.com',
    androidClientId: '806810511020-l0l33tje27n2fio4e0vdkn75m26a8n62.apps.googleusercontent.com',
    iosClientId: '806810511020-coiqoj23j7ssb4k6lc3rg8uc48adueie.apps.googleusercontent.com',
    iosBundleId: 'com.application.nftFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkW_GzvW_Vby2FoeW_JHW4WMLs2eT7De8',
    appId: '1:806810511020:web:1fe9d2f38f7528c7956109',
    messagingSenderId: '806810511020',
    projectId: 'nft-project-9e107',
    authDomain: 'nft-project-9e107.firebaseapp.com',
    storageBucket: 'nft-project-9e107.appspot.com',
    measurementId: 'G-2JC23E3WQ3',
  );
}
